### ISSUE TITLE
不要なPostは削除できると嬉しい

### ISSUE THREAD

**Issue by hi6o** [yochiyochirb/kawaiichan#27]
間違えて作成したPostや、不要になったPostを削除できると、必要なPostを見つけられやすくなるため嬉しい。
controllersにdestroyはあるため、viewに削除ボタンを作成するのが良いように思える。

**Comment by 5t111111** [comment]
edit 画面には削除ボタンがあります！

**Comment by hi6o** [comment]
確認しました、失礼しました！
