### ISSUE TITLE
post の詳細画面では URL はリンクになってほしい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kawaiichan#31]
そのままアクセスできたら便利だから 🍰

**Comment by 5t111111** [comment]
残念ながら何もしなくても自動で URL をリンクにしてくれる機能は Kramdown にはありません。

```
<http://example.com>
```

と `< ... >` で書く必要があります。

自動リンク欲しいのなら redcarpet にパーサーを変えるかなー、という感じ。
