### ISSUE TITLE
前回からの変更点を知りたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kawaiichan#34]
誰でもどのようにでも編集できるから、

- いつ
- だれが
- どのような

変更をしたかがわかるようにしたい。

**Comment by yucao24hours** [comment]
https://yochiyochirb.slack.com/archives/kawaiikawaiichan/p1465294458000019

**Comment by 5t111111** [comment]
refs.
https://github.com/airblade/paper_trail
